export const ALLOWED_THEMES = ['green', 'beige', 'blue', 'pink'] as const;

export const ALLOWED_TAGS = [
  'AI',
  'API',
  'AWS',
  'Accessibility',
  'Angular',
  'Animations',
  'Architecture',
  'Astro',
  'Azure',
  'Backend',
  'CI/CD',
  'CSS',
  'Certification',
  'Conference',
  'Database',
  'Docker',
  'Firebase',
  'Framework',
  'Frontend',
  'IDE',
  'Java',
  'JavaScript',
  'Kotlin',
  'Library',
  'Lit',
  'Logging',
  'Next',
  'Node',
  'Nuxt',
  'Performance',
  'Protocols',
  'Qwik',
  'React',
  'Security',
  'Spring Boot',
  'Storybook',
  'Svelte',
  'Testing',
  'TypeScript',
  'UI/UX',
  'Versioning',
  'Vue',
] as const;

export type Tag = (typeof ALLOWED_TAGS)[number];
