name: Main Build

on:
  push:
    branches: ['master']
  schedule:
    - cron: '0 7 * * 2,4' # At 07:00 on Tuesday and Thursday

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Update YouTube data
        run: node src/scripts/youtube.js
      - name: Update Jobs data
        run: node src/scripts/jobs.js
      - name: Commit and Push updated json files to the repository
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: 'data'
          default_author: github_actions
          new_branch: 'master'
          commit: '--no-verify'
          message: 'chore(data): update YouTube and jobs files'
