name: Main build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 7 * * 2,4' # At 07:00 on Tuesday and Thursday

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v2
      - name: Setup NodeJs 20.x
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Update YouTube data
        run: node src/scripts/youtube.js
      - name: Update Jobs data
        run: node src/scripts/jobs.js
      - name: Commit and Push updated json files to the repository
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data'
          default_author: github_actions
          commit: '--no-verify'
          message: 'chore(data): update YouTube and jobs files'
